// <auto-generated />
using CritConfirmed.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CritConfirmed.Migrations
{
    [DbContext(typeof(CCDbContext))]
    partial class CCDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CritConfirmed.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Agility");

                    b.Property<int>("Body");

                    b.Property<int>("Charisma");

                    b.Property<int>("Edge");

                    b.Property<int>("Essence");

                    b.Property<int>("Intuition");

                    b.Property<int>("Logic");

                    b.Property<int>("Magic");

                    b.Property<int>("MetaType");

                    b.Property<string>("Name");

                    b.Property<int>("Reaction");

                    b.Property<int>("Resonance");

                    b.Property<int>("Strength");

                    b.Property<int>("Willpower");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
